name: smartContract

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Contract/tests
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - run: npm ci
    - run: npm test
